name: PR Checks
on:
  push:
    branches:
      - main
      - dev/*
  pull_request:
jobs:
  'Checking':
    runs-on: macos-latest
    steps:
      - name: '        Git Checkout'
      - uses: actions/checkout
      - name: '        Install Dependencies'
        shell: bash
        run: |
          pnpm install
      - name: '        Lint CSS'
        shell: bash
        run: |
          pnpm run lint:css
      - name: '        Lint JS/TS'
        shell: bash
        run: |
          pnpm run lint:eslint
      - name: '        Lint Markdown'
        shell: bash
        run: |
          pnpm run lint:json
