name: PR Checks
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  'Checking':
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: '        Startup ChromeDriver and Display in Ubuntu'
        shell: bash
        if: matrix.os == 'ubuntu-latest'
        run: |
          export DISPLAY=:99
          # TODO: need to download driver according to electron's version
          wget --directory-prefix=/tmp https://chromedriver.storage.googleapis.com/100.0.4896.20/chromedriver_linux64.zip
          unzip -d /tmp/chromedriver /tmp/chromedriver_linux64.zip
          sudo chmod +x /tmp/chromedriver/chromedriver
          # Fix not being able to run electron on CI https://github.com/microsoft/playwright/issues/34251#issuecomment-2580645333
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
          /tmp/chromedriver/chromedriver &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
      - name: Setup pnpm
      - name: '        Install Dependencies'
        shell: bash
        run: |
          pnpm install
      - name: '        Lint'
        shell: bash
        run: |
          pnpm run lint
