name: Lint

on:
  push:
    branches: [ "devel", "dev/*" ]
  pull_request:
    branches: [ "main", "devel" ]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 1

      - name: Lint
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "devel"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Strict TSLint
        uses: aaomidi/gh-action-tslint@master
